TesteNovaVida/Models/ErrorViewModel.cs
using System;

namespace TesteNovaVida.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TesteNovaVida/Controllers/AlunoController.cs
using BLL;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using ModelFactory;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TesteNovaVida.Util;

namespace TesteNovaVida.Controllers
{
    public class AlunoController : MasterController
    {
        private readonly AlunoBLL oBLL;
        private readonly ProfessorBLL pBLL;
        public AlunoController(IConfiguration configuration)
        {
            this._configuration = configuration;
            ConfigurarAplicacao();
            this.oBLL = new AlunoBLL(_connectionString);
            this.pBLL = new ProfessorBLL(_connectionString);
        }
        public IActionResult Index(int? idProfessor = null)
        {
            var alunos = idProfessor == null ?
                oBLL.SelecionarTodos() :
                oBLL.SelecionarPorProfessor(idProfessor.Value);

            if (idProfessor != null)
            {
                ViewBag.Professor = pBLL.SelecionarProfessor(idProfessor.Value);
            }
            return View(alunos);
        }
        public void CarregaViewBagsCadastrar()
        {
            ViewBag.Professores = pBLL.SelecionarTodos()
                .Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Nome
                }).ToList();
        }
        public IActionResult Cadastrar(int? idProfessor = null)
        {            
            var aluno = new Aluno();
            if (idProfessor != null)
            {
                aluno.Professor = pBLL.SelecionarProfessor(idProfessor.Value);
            }
            CarregaViewBagsCadastrar();
            return View(aluno);
        }
        [HttpPost]
        public IActionResult Cadastrar(Aluno aluno)
        {
            CarregaViewBagsCadastrar();
            var permiteLote = PermiteLote(aluno);
            if (!permiteLote.Sucesso)
            {
                MostraInfo(permiteLote.Mensagem);
                return View(aluno);
            }
            var validacao = oBLL.Cadastrar(aluno);
            if (validacao.Sucesso)
            {
                MostraSucesso("Cadastro realizado com sucesso");
                if(aluno.Anexo != null)
                {
                    var data = DateTime.Now.AddSeconds(RetornaTempoPermiteLote());
                    HttpContext.Session.SetObject<DateTime>($"PROFESSOR_{aluno.Professor.Id}", data);
                }
                return RedirectToAction("Cadastrar");
            }
            MostraErro(validacao.Mensagem);
            return View(aluno);
        }
        [HttpPost]        
        public JsonResult Excluir(int idAluno)
        {
            var retorno = oBLL.ExcluirAluno(idAluno);
            return Json(retorno);            
        }
        public RetornaValidacao PermiteLote(Aluno aluno)
        {
            var retorno = new RetornaValidacao();
            retorno.Sucesso = true;
            if(aluno.Anexo != null)
            {
                var dataLote = HttpContext.Session.GetObject<DateTime>($"PROFESSOR_{aluno.Professor.Id}");
                if(dataLote > DateTime.Now && dataLote != DateTime.MinValue)
                {
                    retorno.Sucesso = false;
                    retorno.Mensagem = $"Você realizou um cadastro de lote com este professor a pouco tempo, você poderá fazer novamente outro lote em {dataLote.ToString()}";
                }
            }
            return retorno;
        }
        public int RetornaTempoPermiteLote()
        {
            return int.Parse(_configuration.GetValue<string>("TimeOutImportacao"));
        }
    }
}

TesteNovaVida/Controllers/HomeController.cs
using BLL;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using ModelFactory;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TesteNovaVida.Models;

namespace TesteNovaVida.Controllers
{
    public class HomeController : MasterController
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ProfessorBLL oBLL;
        public HomeController(ILogger<HomeController> logger, IConfiguration configuration)
        {
            _logger = logger;
            _configuration = configuration;
            ConfigurarAplicacao();
            oBLL = new ProfessorBLL(_connectionString);
        }

        public IActionResult Index()
        {
            var viewModel = oBLL.SelecionarTodos();            
            return View(viewModel);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TesteNovaVida/Controllers/MasterController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TesteNovaVida.Controllers
{
    public class MasterController : Controller
    {
        public IConfiguration _configuration;
        public string _connectionString;        

        public void ConfigurarAplicacao()
        {
            this._connectionString = _configuration.GetValue<string>("ConnectionStrings:DefaultConnection");
        }
        public void MostraErro(string Mensagem)
        {
            TempData["MostraErro"] = Mensagem;
        }
        public void MostraSucesso(string Mensagem)
        {
            TempData["MostraSucesso"] = Mensagem;            
        }
        public void MostraInfo(string Mensagem)
        {
            TempData["MostraInfo"] = Mensagem;            
        }

    }
}

TesteNovaVida/Controllers/ProfessorController.cs
using BLL;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using ModelFactory;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TesteNovaVida.Controllers
{
    public class ProfessorController : MasterController
    {        
        private readonly ProfessorBLL oBLL;
        public ProfessorController(IConfiguration configuration)
        {
            this._configuration = configuration;
            ConfigurarAplicacao();
            this.oBLL = new ProfessorBLL(_connectionString);
        }
        public IActionResult Index()
        {
            return RedirectToAction("Index","Home");
        }
        public IActionResult Cadastrar()
        {            
            return View(new Professor());
        }
        [HttpPost]
        public IActionResult Cadastrar(Professor professor)
        {
            if (ModelState.IsValid)
            {
                var validacao = oBLL.Cadastrar(professor);
                if (validacao.Sucesso)
                {
                    MostraSucesso("Cadastro realizado com sucesso");
                    return RedirectToAction("Cadastrar");
                }
                MostraErro(validacao.Mensagem);
            }
            return View(professor);
        }
    }
}

TesteNovaVida/Views/Aluno/Cadastrar.cshtml
@model ModelFactory.Aluno
@{
    ViewData["Title"] = "Home Page";
}

<div class="card">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-m12 p-3">
        <h5 class="card-title">Cadastrar Alunos</h5>
        <form id="form-cadastro" asp-action="Cadastrar" enctype="multipart/form-data">
            <div class="row input-group">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-m12">
                    <button type="button" class="btn btn-primary btn-sm" onclick="$('#Anexo').click()">Importe uma Lista</button>
                </div>
                <hr />
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-m12 pt-3">
                    <h6 class="card-subtitle mb-2 text-muted">Ou insira um novo cadastro</h6>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-m12 pt-3">
                    <label asp-for="Professor.Nome"></label>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-m12">
                    @Html.DropDownListFor(x => x.Professor.Id, (List<SelectListItem>)ViewBag.Professores, "- SELECIONE UM PROFESSOR -", new { @class = "form-select", required = "required" })
                    <span asp-validation-for="Professor.Id" class="text-danger"></span>
                    <span asp-validation-for="Professor.Id" class="text-danger"></span>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-m12">
                    <label asp-for="Nome"></label>
                    <input asp-for="Nome" maxlength="200" class="form-control" required />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-m12">
                    <label asp-for="ValorMensalidade"></label>
                    <input asp-for="ValorMensalidade" class="form-control decimal" required />
                    <span asp-validation-for="ValorMensalidade" class="text-danger"></span>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-m12">
                    <label asp-for="DataVencimento"></label>
                    <input asp-for="DataVencimento" type="date" class="form-control" required />
                    <span asp-validation-for="DataVencimento" class="text-danger"></span>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-m12 mt-3">
                    <input type="file" class="invisible" asp-for="Anexo" onchange="PreparaSubmitLista()" accept=".txt" />
                </div>
            </div>
            <div class="row pt-1">
                <div class="col-xs-12 col-sm-12 col-md-4 col-lg-m2">

                    <button type="submit" class="btn btn-primary btn-sm">Cadastre</button>
                </div>
            </div>
        </form>
    </div>
</div>

@section scripts {
    <script type="text/javascript">
        function PreparaSubmitLista() {
            var bProfessorSelecionado = $('#Professor_Id').val() != "";
            var bPossuiAnexo = $('#Anexo').val() != "";
            if (!bProfessorSelecionado && bPossuiAnexo) {
                mostraDialogo("Antes de exportar uma lista, é necessário selecionar um professor!", "info");
                return;
            }
            if (bPossuiAnexo) {
                $('#form-cadastro').submit();
            }
        }
    </script>
}

TesteNovaVida/Views/Aluno/Index.cshtml
@model List<ModelFactory.Aluno>
@{
    ViewData["Title"] = "Home Page";
}

<div class="card">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-m12 p-3 overflow-hidden">
        <h5>Lista de Alunos @(ViewBag.Professor != null ? (" - Professor: " + ViewBag.Professor.Nome) : "")</h5>
        <table id="dtCadastros"></table>
    </div>
</div>

@section scripts {
    <script type="text/javascript">
        var table =
            $("#dtCadastros").DataTable(
                {
                    autoWidth: false,
                    dom: 'Bfrtip',
                    responsive: true,
                    buttons: [
                        {
                            text: 'Novo',
                            action: function (e, dt, node, config) {
                                Novo();
                            }
                        }
                    ],
                    columns: [
                        { data: 'Acao', title: '', orderable: false },
                        { data: "Id", title: "", visible: false },
                        { data: "IdProfessor", title: "", visible: false },
                        { data: "NomeAluno", title: "Aluno"  },
                        { data: "ValorMensalidade", title: "Valor Mensalidade"  },
                        { data: "DataVencimento", title: "Data Vencimento"  },
                        { data: "NomeProfessor", title: 'Professor' }
                    ],                    
                    language: LanguageDataTables
                }
            );

        function AddRowsCadastros(Id, IdProfessor, NomeAluno, ValorMensalidade, DataVencimento, NomeProfessor) {
            table.row.add(
                {
                    Acao: "<a class='tooltipped' data-position='bottom'data-html='true' data-tooltip='Editar'><i class='fas fa-trash' onclick='ExcluirAluno(" + Id + ", this)'></i></a>",
                    Id: Id,
                    IdProfessor: IdProfessor,
                    NomeAluno: NomeAluno,
                    ValorMensalidade: ValorMensalidade,
                    DataVencimento: DataVencimento,
                    NomeProfessor: NomeProfessor,
                }
            ).draw(true);
        }

        function Novo() {
            var IdProfessor = '@(ViewBag.Professor != null ? ViewBag.Professor.Id : "")'
            if (IdProfessor > 0) {
                window.location = "@Url.Action("Cadastrar","Aluno")?idProfessor=" + IdProfessor;
            } else {
                window.location = "@Url.Action("Cadastrar", "Aluno")";
            }
        }

        var row;
        function ExcluirAluno(IdAluno, el) {
            var row = table.row($(el).closest('tr'));
            $.ajax({
                type: "POST",
                url: "@Url.Action("Excluir", "Aluno")",
                data: {
                    idAluno: IdAluno
                },                
                success: function (e) {
                    debugger;
                    mostraDialogo(e.mensagem, e.sucesso ? "success" : "danger");
                    if (e.sucesso) {
                        row.remove().draw();
                    }
                },
                failure: function (response) {
                    mostraDialogo(responde, 'danger');
                },
                error: function () {
                    mostraDialogo("Houve um erro inesperado", 'danger');
                }
            });
        }
        @foreach (var item in Model)
        {
        <text>
        AddRowsCadastros('@item.Id'
            , '@item.Professor.Id'
            , '@item.Nome'
            , '@item.ValorMensalidade.ToString("c2")'
            , '@item.DataVencimento.ToShortDateString()'
            , '@item.Professor.Nome'
         );
        </text>
        }
    </script>
}

TesteNovaVida/Views/Home/Index.cshtml
@model List<ModelFactory.Professor>
@{
    ViewData["Title"] = "Home Page";
}

<div class="card">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-m12 p-3">
        <h5>Lista de Professores</h5>
        <table id="dtCadastros"></table>
    </div>
</div>

@section scripts {
    <script type="text/javascript">

        var table =
            $("#dtCadastros").DataTable(
                {
                    autoWidth: false,
                    dom: 'Bfrtip',
                    responsive: true,
                    buttons: [
                        {
                            text: 'Novo',
                            action: function (e, dt, node, config) {
                                Novo();
                            }
                        }
                    ],
                    columns: [
                        { data: 'Acao', title: '', orderable: false },
                        { data: "Id", title: "", visible: false },
                        { data: "NomeProfessor", title: 'Professor' }
                    ],
                    language: LanguageDataTables
                }
            );

        function AddRowsCadastros(Id, NomeProfessor) {
            table.row.add(
                {
                    Acao: "<a class='tooltipped' data-position='bottom'data-html='true' data-tooltip='Editar'><i class='fas fa-list' onclick='ListarAlunos(" + Id + ")'></i></a>",
                    Id: Id,
                    NomeProfessor: NomeProfessor
                }
            ).draw(true);
        }

        function Novo() {
            window.location = "@Url.Action("Cadastrar","Professor")"; 
        }

        function ListarAlunos(IdProfessor) {
            window.location = "@Url.Action("Index","Aluno")?idProfessor=" + IdProfessor;
        }
        @foreach (var item in Model)
        {
        <text>
        AddRowsCadastros('@item.Id', '@item.Nome');
        </text>
        }
    </script>
}

TesteNovaVida/Views/Professor/Cadastrar.cshtml
@model ModelFactory.Professor
@{
    ViewData["Title"] = "Home Page";
}

<div class="card">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-m12 p-3">
        <h5>Cadastrar Professor</h5>
        <form id="form-cadastro" asp-action="Cadastrar">
            <div class="row input-group">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-m12">
                    <label asp-for="Nome" ></label>
                    <input asp-for="Nome" maxlength="200" class="form-control" required/>
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
            </div>
            <div class="row pt-2">
                <div class="col-xs-12 col-sm-12 col-md-4 col-lg-m2">
                    <button type="submit" class="btn btn-primary btn-sm">Cadastrar</button>
                </div>
            </div>
        </form>
    </div>
</div>

@section scripts {
    <script type="text/javascript">

    </script>
}

TesteNovaVida/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Teste Técnico</title>    
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/datatables/css/dataTables.css" />
    <link rel="stylesheet" href="~/lib/datatables/css/buttons.dataTables.css" />  
    <script src="~/lib/font/fontawesome.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Teste Técnico</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">
                                <i class='fas fa-home'></i>
                                <span class="pl-1">Professores</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Aluno" asp-action="Index">Alunos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Teste Técnico - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.mask.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/datatables/js/dataTables.js"></script>    
    <script src="~/lib/datatables/js/dataTables.responsive.js"></script>    
    <script src="~/lib/datatables/js/dataTables.buttons.js"></script>
    <script src="~/lib/datatables/js/dataTables.html5.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>   
    @RenderSection("Scripts", required: false)
    @{Html.RenderPartial("_MensagensPartial");}
</body>
</html>

TesteNovaVida/Views/Shared/_MensagensPartial.cshtml
@{
    Layout = null;
}
<script type="text/javascript">
    $(document).ready(function () {
        @if (TempData["MostraErro"] != null)
        {
            <text>
                mostraDialogo("@TempData["MostraErro"]", "danger");
            </text>
        }

        @if (TempData["MostraSucesso"] != null)
        {
            <text>
                mostraDialogo("@TempData["MostraSucesso"]", "success");
            </text>
        }

        @if (TempData["MostraInfo"] != null)
        {
            <text>
                mostraDialogo("@TempData["MostraInfo"]", "info");
            </text>
        }
    })
</script>